site_name: Blog Template
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  hljs_languages:
    - yaml
    - json
  features:
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
plugins:
  - search
  - blogging:
      dirs:
        - blog
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.pathconverter:
      base_path: mwclouddev
      relative_path: docs
      absolute: false # default is false
extra:
  tags:
    GitHub: github
    AWS: aws
    Python: python
    YAML: yaml
    JSON: json
    Terraform: terraform
    Ansible: ansible
    CloudFormation: cfn
nav:
  - Home: index.md
  - Blog:
      - Blog: blog/index.md
